import React from 'react'
import { useState, useEffect } from 'react'
import { useSelector } from 'react-redux'
import "../../styles/Report.css"
import { useParams } from 'react-router-dom'
import meetServices from '../../services/meetServices'

function Report() {
  const { meetingid } = useParams();
  const userData = useSelector((state) => state.auth)
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    const fetchReport = async () => {
      try {
        setLoading(true)
        const data = await meetServices.getReport(meetingid);
        setReport(data)
        setError(null)
      } catch (err) {
        console.error("Error fetching report:", err);
        setError("Failed to load report")
      } finally {
        setLoading(false)
      }
    };
    fetchReport();
  }, [meetingid])

  if (loading) {
    return <div className='report-content'><p>Loading report...</p></div>
  }

  if (error || !report || report.message) {
    return <div className='report-content'><p>{error || "No report available"}</p></div>
  }

  return (
    <div className='report-content'>
      <div className="report-container">
        <div className="report-header">
          <h2>{report.title}</h2>
          <p className="report-date">Generated on: {new Date(report.created_at).toLocaleDateString()}</p>
          <p className="report-by">Generated by: {report.generated_by_name}</p>
        </div>

        {report.summary && (
          <section className="report-section">
            <h3>Summary</h3>
            <p>{report.summary}</p>
          </section>
        )}

        {report.attendees && report.attendees.length > 0 && (
          <section className="report-section">
            <h3>Attendees</h3>
            <table className='report-table'>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {report.attendees.map((attendee, index) => (
                  <tr key={index}>
                    <td>{attendee.username}</td>
                    <td><button className={`report-status-btn ${attendee.attended ? 'attended' : 'absent'}`}>
                      {attendee.attended ? 'ATTENDED' : 'ABSENT'}
                    </button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {report.keyDecisions && report.keyDecisions.length > 0 && (
          <section className="report-section">
            <h3>Key Decisions</h3>
            <ul>
              {report.keyDecisions.map((decision, index) => (
                <li key={index}>{decision}</li>
              ))}
            </ul>
          </section>
        )}

        {report.actionItems && report.actionItems.length > 0 && (
          <section className="report-section">
            <h3>Action Items</h3>
            <ul>
              {report.actionItems.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>
        )}
      </div>
    </div>
  )
}

export default Report